build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
labels:
  org.opencontainers.image.title: "LUFTaTOR"
  org.opencontainers.image.description: "LUFTaTOR Home Assistant add-on"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.source: "https://github.com/luftuj-cz/home-assistant"
